import './globals.css'
import { Header, Footer } from '@/components'

export const metadata = {
  title: 'Ninja Player - Blogs',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Header/>
        {children}
        <Footer/>
      </body>
    </html>
  )
}
